### ISSUE TITLE
Create CV and contacts screen UI

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#112]
Create CV and contacts screen UI, use this component on this screen: https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/111

User story:

As a talent, I want to be able to fill up a profile by contact information, so that potential employers can access my information after contact is occurred.

Acceptance criteria:

- CV and contacts page must include input fields for “Full name”, “Phone number”, “Linkedin profile”
- [The “Full name”, “Phone number”, “Linkedin profile” and “CV” must be required and have “*”
- The “Full name”, “Phone number” should have a placeholder
- Page must contain “Choose photo” button to add photo
- When talent clicks on “Choose photo” button should be 2 options: launch gallery or take picture from camera 
- Allowed image file formats should be jpeg, png, jpg
- The “Full name” field should be between 3 and 50 characters in length
- The “Full name” must accept A-Z, a-z, (.), ('), (-), spaces, if the talent typed a special characters or numbers, should see a validation message
- The “Phone number” must start "+" symbol at the beginning of the number
- The “Phone number” should allow of 10 digits
- The “Phone number” field must accept only accept numeric input
- Error message to display if the validation rule is not met for the “Phone number” field 
- Talent should be able to add URL for Linkedin profile, if the talent typed invalid URL, should see a validation message
- "Linkedin profile" field should accept A-Z, a-z, 0-9, special chars
- "Linkedin profile" field  must consist of: https://www.linkedin.com/in/ + >0 symbols
- Size limit for CV files and photo 5 MB
- Page must contain “Choose file” button to add CV file
- When talent clicks on “Choose file” button should be able to choose file from device 
- Allowed types for CV file should be docx, doc, pdf
- Talent should be able to back to the previous step "Skills and projects" by clicking on the “Back” button
- Talent should be able to go to the next step "Preview" by clicking on the “Next” button
- Talent 's information should be saved in the fields when switching between steps
- The registration step “STEP 04/05” is placed in the upper right corner on the same line with the title “CV and contacts”

![Image](https://user-images.githubusercontent.com/103518438/263261386-33bbcb86-3102-46bb-86a6-ab1f163205c4.png)

**Comment by anna9314** [comment]
User story:

As a talent, I want to be able to fill up a profile by contact information, so that potential employers can access my information after contact is occurred.

Acceptance criteria:

- CV and contacts page must include input fields for “Full name”, “Phone number”, “Linkedin profile”
- [The “Full name”, “Phone number”, “Linkedin profile” and “CV” must be required and have “*”
- The “Full name”, “Phone number” should have a placeholder
- Page must contain “Choose photo” button to add photo
- When talent clicks on “Choose photo” button should be 2 options: launch gallery or take picture from camera 
- Allowed image file formats should be jpeg, png, jpg
- The “Full name” field should be between 3 and 50 characters in length
- The “Full name” must accept A-Z, a-z, (.), ('), (-), spaces, if the talent typed a special characters or numbers, should see a validation message
- The “Phone number” must start "+" symbol at the beginning of the number
- The “Phone number” should allow of 10 digits
- The “Phone number” field must accept only accept numeric input
- Error message to display if the validation rule is not met for the “Phone number” field 
- Talent should be able to add URL for Linkedin profile, if the talent typed invalid URL, should see a validation message
- "Linkedin profile" field should accept A-Z, a-z, 0-9, special chars
- "Linkedin profile" field  must consist of: https://www.linkedin.com/in/ + >0 symbols
- Size limit for CV files and photo 5 MB
- Page must contain “Choose file” button to add CV file
- When talent clicks on “Choose file” button should be able to choose file from device 
- Allowed types for CV file should be docx, doc, pdf
- Talent should be able to back to the previous step "Skills and projects" by clicking on the “Back” button
- Talent should be able to go to the next step "Preview" by clicking on the “Next” button
- Talent 's information should be saved in the fields when switching between steps
- The registration step “STEP 04/05” is placed in the upper right corner on the same line with the title “CV and contacts”

**Comment by anna9314** [comment]
Blocked
Next/Back buttons don't work yet to go to the "CV and contacts" step

**Comment by ed9ward** [comment]
Tested
Added BR
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/392
