### ISSUE TITLE
Create badge component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2023-bsa-talents#117]
![Image](https://user-images.githubusercontent.com/78347072/263462749-740d79eb-d0d2-49bd-9fb0-7422be1b5070.png)

![Image](https://user-images.githubusercontent.com/78347072/263462758-56ecb10b-597e-4b4f-844c-a5c5ec586b12.png)

**Comment by JemiJe** [comment]
can we use for example https://mui.com/material-ui/material-icons/?query=head&theme=Outlined&selected=HeadphonesOutlined
material UI icons, or it must be exactly like on figma? I saw we use mui icons in, for example modal component

**Comment by JemiJe** [comment]
additionally, are they finit number of badge types or should be more extensible and we can freely choose color and text independently of content of badge? 
I mean, when we use component we should choose type of it (english, communication...) or we can set our custom numbers, description and color? And no need to hardcode all of it into enams/types.
Because if in project appears new badges it will be hard to change and add new ones. So better to make them extensible.
