### ISSUE TITLE
Create Material UI theme with our custom colors

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-2023-bsa-talents#2]
![Image](https://user-images.githubusercontent.com/105710998/261575710-86821601-e277-4b26-adc9-874ef6f47b21.png)

Info: https://mui.com/material-ui/customization/color/
Design: https://www.figma.com/file/Yd7USgP7PLvA0W794jHXWu/BSA_recruting?type=design&node-id=0-1&mode=design&t=mvb2tCBVBeWTg5yG-0

**Comment by Simpsonkk** [comment]
@anton-otroshchenko 
Hi! I added custom props in MUI theme but MUI requires interfaces instead of type, can I add /* eslint-disable @typescript-eslint/consistent-type-definitions */ ?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/92392661/f7736488-ee6b-4cac-9aa1-eee04d96296e)


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/92392661/c4f0ef37-b67b-4580-8937-e8016a0eff9a)
