### ISSUE TITLE
Create chat list screen

### ISSUE THREAD

**Issue by katerynakostikova** [BinaryStudioAcademy/bsa-2023-bsa-talents#422]
**User story:**
As a user, I want to have a chat list, so that I am able to find the dialogue with potential employers.

**Acceptance criteria:**
- There should be the “Chats” name of the page in the upper left corner
- The chat list must include an input field for the search field on the top
- There should be a placeholder for the search field 
- A list of users’ chats should be displayed below the search field
- When the user writes a search query, only chats for my search query are displayed
- When the user selects chat (tap on it) it should somehow be highlighted and open in a new window
- Every chat should be displayed with the user’s profile photo, user name, the last message and the last message time of delivery
- When the user  taps on the chat it should open in a new screen

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/e770358c-8ac9-4655-afaa-e0aac09882d5)

**Comment by katerynakostikova** [comment]
@anogire If someone messages to the user, the message should appear on that screen without the screen reloading

**Comment by anogire** [comment]
I don't quite understand the requirement "When the user selects the search field it should be highlighted".
I made it so that the found messages are highlighted, is that correct?
<img width="385" alt="Screenshot 2023-09-19 at 02 20 49" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/4763b323-57e3-4a68-b651-78e975ce3927">

**Comment by anna9314** [comment]
Yes, it's correct. I will check criteria and rewrite them, something should be only for web

**Comment by anogire** [comment]
Ok, thank you. So I don't need to filter the search results and leave only those messages that are found? 
All messages remain in place, but the ones that are found are highlighted.

**Comment by anna9314** [comment]
Sorry, didn't catch it at first. Now I got it
I think it is better to filter, show the message that was requested, because there may be many similar ones and then the user will have to scroll a lot.

If we show a message on request, then you can not highlight it, because only those that are of interest to us will be shown

**Comment by anogire** [comment]
So then for mobile, I don't highlight them at all, because when you click on them, you will go to a new chat screen with this user and you won't see a list with a highlighted message.

**Comment by anna9314** [comment]
when the user writes a search query, only chats for my search query are displayed. When the user selects chat (tap on it) it should somehow be highlighted and open in a new window

**Comment by katerynakostikova** [comment]
Build in 15 min

**Comment by katerynakostikova** [comment]
https://bsa2023.slack.com/archives/C05PZJMEV8V/p1695290403651929

**Comment by ed9ward** [comment]
Tested
